In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score as score
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
movie=pd.read_csv("/content/IMDb Movies India.csv", sep=',', encoding='latin')#load the dataset from kaggle

In [ ]:
movie.head()#displaying the upper 5 values

Name    Year Duration            Genre  \
0                                         NaN      NaN            Drama   
1  #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama   
2                         #Homecoming  (2021)   90 min   Drama, Musical   
3                             #Yaaram  (2019)  110 min  Comedy, Romance   
4                   ...And Once Again  (2010)  105 min            Drama   

   Rating Votes            Director       Actor 1             Actor 2  \
0     NaN   NaN       J.S. Randhawa      Manmauji              Birbal   
1     7.0     8       Gaurav Bakshi  Rasika Dugal      Vivek Ghamande   
2     NaN   NaN  Soumyajit Majumdar  Sayani Gupta   Plabita Borthakur   
3     4.4    35          Ovais Khan       Prateik          Ishita Raj   
4     NaN   NaN        Amol Palekar  Rajat Kapoor  Rituparna Sengupta   

           Actor 3  
0  Rajendra Bhatia  
1    Arvind Jangid  
2       Roy Angana  
3  Siddhant Kapoor  
4      Antara Mali

In [ ]:
movie.describe()#describing its statics

Rating
count  7919.000000
mean      5.841621
std       1.381777
min       1.100000
25%       4.900000
50%       6.000000
75%       6.800000
max      10.000000

In [ ]:
movie.info()#display the information of data set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      15509 non-null  object 
 1   Year      14981 non-null  object 
 2   Duration  7240 non-null   object 
 3   Genre     13632 non-null  object 
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object 
 6   Director  14984 non-null  object 
 7   Actor 1   13892 non-null  object 
 8   Actor 2   13125 non-null  object 
 9   Actor 3   12365 non-null  object 
dtypes: float64(1), object(9)
memory usage: 1.2+ MB


In [ ]:
movie.isna().sum()#checking for null full and summ up them to show a single value of each

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [ ]:
movie=movie.dropna()#drouping null values

In [ ]:
fs=['Genre',"Director","Actor 1","Actor 2","Actor 3"]#data converting into target and features form like input and output form
target="Rating"
movie=movie[fs+[target]].dropna()

In [ ]:
movie.shape

(5659, 6)

In [ ]:
cf=['Genre',"Director","Actor 1","Actor 2","Actor 3"]#column which is needed for futher calculation
lb=OneHotEncoder()#it will tranform the dtaa in 0 and 1
from sklearn.compose import ColumnTransformer#it will again concate the dataa

tx=ColumnTransformer([("lb",lb,cf)],remainder="passthrough")
t=tx.fit_transform(movie)#fiting the data
t
pd.DataFrame(t)
#making its dataframe
data_encoded=pd.get_dummies(movie[['Genre',"Director","Actor 1","Actor 2","Actor 3"]])
data_encoded

Genre_Action  Genre_Action, Adventure  \
1                 0                        0   
3                 0                        0   
5                 0                        0   
6                 0                        0   
8                 0                        0   
...             ...                      ...   
15493             0                        0   
15494             0                        0   
15503             0                        0   
15505             0                        0   
15508             0                        0   

       Genre_Action, Adventure, Biography  Genre_Action, Adventure, Comedy  \
1                                       0                                0   
3                                       0                                0   
5                                       0                                0   
6                                       0                                0   
8                                       0                                0   
...                                   ...                              ...   
15493                                   0                                0   
15494                                   0                                0   
15503                                   0                                0   
15505                                   0                                0   
15508                                   0                                0   

       Genre_Action, Adventure, Crime  Genre_Action, Adventure, Drama  \
1                                   0                               0   
3                                   0                               0   
5                                   0                               0   
6                                   0                               0   
8                                   0                               0   
...                               ...                             ...   
15493                               0                               0   
15494                               0                               0   
15503                               0                               0   
15505                               0                               0   
15508                               0                               0   

       Genre_Action, Adventure, Family  Genre_Action, Adventure, Fantasy  \
1                                    0                                 0   
3                                    0                                 0   
5                                    0                                 0   
6                                    0                                 0   
8                                    0                                 0   
...                                ...                               ...   
15493                                0                                 0   
15494                                0                                 0   
15503                                0                                 0   
15505                                0                                 0   
15508                                0                                 0   

       Genre_Action, Adventure, History  Genre_Action, Adventure, Horror  ...  \
1                                     0                                0  ...   
3                                     0                                0  ...   
5                                     0                                0  ...   
6                                     0                                0  ...   
8                                     0                                0  ...   
...                                 ...                              ...  ...   
15493                                 0                                0  ...   
15494                                 0                

In [ ]:
from sklearn.model_selection import train_test_split
Xtrain,xtest,Ytrain,ytest=train_test_split(t,movie[target],test_size=0.50)#spliting the data by size of testing = 50%


In [ ]:
model=LinearRegression()
model.fit(Xtrain,Ytrain)#fiting the model
ypred=model.predict(xtest)
ytest

In [ ]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(ytest,ypred)#finfing the accuracy
mse


2.127718870390672e-07

In [ ]:
from sklearn.metrics import r2_score
r2=r2_score(ytest,ypred)
r2

0.9999998878621089

In [ ]:
#applying different types of algos
DTR = DecisionTreeRegressor(random_state=1)
DTR.fit(Xtrain, Ytrain)
dt_preds = DTR.predict(xtest)


KNR = KNeighborsRegressor(n_neighbors=5)
KNR.fit(Xtrain, Ytrain)
knn_preds = KNR.predict(xtest)



RFR = RandomForestRegressor(n_estimators=100, random_state=1)
RFR.fit(Xtrain, Ytrain)
rf_preds = RFR.predict(xtest)
rf_preds,knn_preds,dt_preds

(array([7. , 7.1, 5. , ..., 4.3, 6.9, 8.4]),
 array([6.8 , 7.04, 5.3 , ..., 5.24, 6.74, 8.4 ]),
 array([7. , 7.1, 5. , ..., 4.3, 6.9, 8.4]))

In [ ]:
#evaluating the accuracy

In [ ]:
def evaluate_model(ytest1,ypred, model_name):
    print("Model: ", model_name)
    print("Accuracy = {:0.2f}%".format(score(ytest1, ypred)*100))
    print("Mean Squared Error = {:0.2f}\n".format(mean_squared_error(ytest1, ypred, squared=False)))

    return round(score(ytest1, ypred)*100, 2)

In [ ]:
LRScore = evaluate_model(ytest, lr_preds, "LINEAR REGRESSION")
RFScore = evaluate_model(ytest, rf_preds, "RANDOM FOREST")
DTScore = evaluate_model(ytest, dt_preds, "DECEISION TREE")
KNNScore = evaluate_model(ytest, knn_preds, "K NEAREST NEIGHBORS")

Model:  LINEAR REGRESSION
Accuracy = 100.00%
Mean Squared Error = 0.00

Model:  RANDOM FOREST
Accuracy = 99.99%
Mean Squared Error = 0.02

Model:  DECEISION TREE
Accuracy = 99.99%
Mean Squared Error = 0.02

Model:  K NEAREST NEIGHBORS
Accuracy = 96.69%
Mean Squared Error = 0.25

